from app.services.failure_service import normalize_failure_record
from app.services.maintenance_service import normalize_maintenance_record
from app.services.sensor_service import compute_machine_health, get_recent_sensor_readings
